django/modelproject/account/urls.py
from django.urls import path
from .views import * 

app_name='account'

urlpatterns=[
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout, name='logout'),
]

django/modelproject/blog/urls.py
from django.urls import path
from blog.views import *

app_name= 'blog'

urlpatterns=[
    path('<int:id>', detail, name='detail'),
    path('new/', new, name='new'),
    path('create/', create, name='create'),
    path("update/<int:id>", update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('new_with_django_form/', new, name='new_with_django_form'),
    path('create_with_django_form/', create, name='create_with_django_form'),
    path('comment_create/<int:id>', comment_create, name='comment_create')
]

django/modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')), 
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/modelproject/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    nickname= models.CharField(max_length=100)
    university= models.CharField(max_length=50)
    location=models.CharField(max_length=200)

django/modelproject/blog/models.py
from django.contrib.auth.models import User
from django.db import models

class Blog(models.Model):
    title= models.CharField(max_length=200)
    writer= models.CharField(max_length=10)
    pub_date= models.DateTimeField()
    body= models.TextField()
    image= models.ImageField(upload_to='blog/', blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

class Comment(models.Model):
    writer= models.CharField(max_length=10)
    content= models.TextField()
    create_date= models.DateTimeField()

django/modelproject/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'nickname', 'university', 'location']

django/modelproject/blog/forms.py
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model= Blog
        fields= ['title', 'writer', 'body', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']

django/modelproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .forms import SignupForm

def login_view(request):
    if request.method== 'POST':
        form= AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username= form.cleaned_data.get('username')
            password= form.cleaned_data.get('password')
            user= auth.authenticate(
                request=request,
                username=username,
                password=password
            )

            if user is not None:
                auth.login(request, user)
                return redirect('home')

        return redirect('account:login')

    else:
        form= AuthenticationForm()
        return render(request, 'login.html', {'form':form})

def logout(request):
    auth.logout(request)
    return redirect('home')

def signup_view(request):
    if request.method== 'POST':
        form= SignupForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth.login(request, user)
            return redirect('home')
        return redirect('account:signup')
    else:
        form= SignupForm()
        return render(request, 'signup.html', {'form':form})

django/modelproject/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from .models import Blog
from .forms import BlogForm, CommentForm
from django.core.paginator import Paginator

def home(request):
    blogs= Blog.objects.order_by('-pub_date')

    query= request.GET.get('query')
    if query:
        blogs= Blog.objects.filter(title__icontains=query)#under_bar 2개임!

    paginator= Paginator(blogs, 3)
    page= request.GET.get('page')
    paginated_blogs= paginator.get_page(page)
    return render(request, 'home.html', {'blogs': paginated_blogs})

def detail(request, id):
    blog= get_object_or_404(Blog, pk= id)
    return render(request, 'detail.html', {'blog': blog})

def new(request):
    return render(request, 'new.html')

def create(request):
    new_blog= Blog()
    new_blog.title= request.POST['title']
    new_blog.writer= request.POST['writer']
    new_blog.body= request.POST['body']
    new_blog.image= request.FILES['image']
    new_blog.pub_date= timezone.now()
    new_blog.save()
    return redirect('blog:detail', new_blog.id)

def update(request, id):
    blog= Blog.objects.get(id=id)
    if request.method== 'POST':
        blog.title= request.POST['title']
        blog.body= request.POST['body']
        blog.save()
        return redirect('detail', blog.id)
    return render(request, 'update.html', {'blog': blog})

def delete(request, id):
    blog= Blog.objects.get(id=id)
    blog.delete()
    return redirect('home')

def new_with_django_form(request):
    form= BlogForm()
    return render(request, 'new_with_django_form.html', {'form':form})

def create_with_django_form(request):
    form= BlogForm(request.POST, request.FILES)
    if form.is_valid():
        new_blog= form.save(commit=False)
        new_blog.pub_date= timezone.now()
        new_blog.save()
        return redirect('home')

def comment_create(request, id):
    blog= Blog.objects.get(id=id)
    form= CommentForm(request.POST)
    if form.is_valid():
        comment= form.save(commit=False)
        comment.create_date= timezone.now()
        comment.save()
        return redirect('detail', blog.id)
    else:
        form= CommentForm()
    context={'form': form}
    return render(request, 'comment_form.html', context)

django/modelproject/account/templates/login.html
{% extends 'base.html' %}
{% block content %}

<div style="text-align: left;">
<h1 style="margin-bottom: 50px;">로그인 페이지</h1>
<form action="{% url 'account:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" style="margin-top: 30px;">로그인</button>
</form>
</div>

{% endblock %}

django/modelproject/account/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: left;">
    <h1 style="margin-bottom: 50px;">회원가입 페이지</h1>
    <form action="{% url 'account:signup' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"  style="margin-top: 30px;">회원가입</button>
    </form>
</div>

{% endblock %}

django/modelproject/blog/templates/comment_form.html
{% extends 'base.html' %}

{% block content %}

<h3>댓글등록하기</h3>
<div>
    <form action="{% url 'blog:comment_create' %}" method="POST">
        {% csrf_token %}
        <label for="content">댓글내용</label>
            {{form.as_p}}
        <button type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

django/modelproject/blog/templates/detail.html
{% extends 'base.html' %}
  {% block content %}
  <body>
    <h1>{{blog.title}}</h1>
    <div>
      작성자: {{blog.writer}}
      <br />
      날짜: {{blog.pub_date}}
    </div>
    <hr />
    <p>{{blog.body}}</p>
    {% if blog.image %}
      <p><img src="{{blog.image.url}}" alt="/"></p>
    {% endif %}
   
    <!-- 코멘트부분 -->
    {% if comment %}
      <span>{{ comment.content }}</span>
      <span>
      - {{ comment.writer }}, {{ comment.create_date }}
    {% endif %}
    </span>
    <div>
      <a href="{% url 'blog:comment_create' blog.id %}"><small>댓글추가</small></a>
    </div>


    <h4><a href="{% url 'home' %}">홈으로</a></h4>
    {% if user.is_authenticated %}
    <h4><a href="{% url 'blog:update' blog.id %}">수정하기</a></h4>
    <h4><a href="{% url 'blog:delete' blog.id%}">삭제하기</a></h4>
    {% endif %}
  </body>
  {% endblock %}

django/modelproject/blog/templates/home.html
{% extends 'base.html' %}
  {% block content %}
  <body style="text-align: left;">
    <h1 style="margin: 20px;">Blog Project</h1>
    <div class='container'>
      {% if user.is_authenticated %}
      {{user.location}}에 사는 {{user.university}}다니는 {{user.nickname}} 안녕하세요!
      {% endif %} 
      {% if user.is_authenticated %}
      <h4 style="text-align: right;"><a href="{% url 'blog:new_with_django_form' %}">글쓰기</a></h4>
      {% endif %}
        {% for blog in blogs %}
        <table class="table table-bordered" style="margin: 5px;">
          <tr>
            <td>
              제목: {{ blog.title }}
            </td>
            <td>
              글쓴이: {{ blog.writer }}
            </td>
            <td>
            내용: {{ blog.summary }}
            </td>  
          </tr>
        </table>
        <div style="text-align: right;">
        <a href="{% url 'blog:detail' blog.id %}" style="margin: 10px;">더보기</a>
        <a href="{% url 'blog:delete' blog.id%}" style="margin: 10px;">삭제하기</a>
        </div>
        {% endfor %}
        <br>
        <div class="paginator" style="text-align: center;">
          {% if blogs.has_previous %}
          <a href="?page=1">처음</a>
          <a href="?page={{blogs.previous_page_number}}">이전</a>
          {% endif %}
          <span>{{blogs.number}}</span>
          <span>of</span>
          <span>{{blogs.paginator.num_pages}}</span>
          {% if blogs.has_next %}
          <a href="?page={{blogs.next_page_number}}">다음</a>
          <a href="?page={{blogs.paginator.num_pages}}">마지막</a>
          {% endif %}
        </div>
    </div>
    </body>
    {% endblock %}

django/modelproject/blog/templates/new.html
{% extends 'base.html' %}
    {% block content %}
    <body>
        <h1>CREATE_YOUR_NEW_POST_HERE!!</h1>
        <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <p>제목: <input type="text" name="title"></p>
            <p>작성자: <input type="text" name="writer"></p>
            <p>사진: <input type="file" name="image"></p>
            본문: <br><textarea name="body" id="" cols="30" rows="10"></textarea><br>
            <button type='submit'>작성하기</button>
        </form>
    </body>
    {% endblock %}

django/modelproject/blog/templates/new_with_django_form.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE_YOUR_NEW_POST_HERE!!</h1>

<form action="{% url 'blog:create_with_django_form' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
</form>
{% endblock %}

django/modelproject/blog/templates/update.html
{% extends 'base.html' %}
    {% block content %}
        <form action="{% url 'blog:update' blog.id %}" method = "POST">
            {% csrf_token %}
        <h4>제목: </h4>
        <input type="text" name="title" value=“{{blog.title}}”>
        <br>
        <br>
        <h4>본문: </h4>
        <textarea name="body" cols="30" rows="10">{{blog.body}}</textarea><br><br>
        <input type="submit" value="완료">
        </form>
    {% endblock %}

django/modelproject/modelproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <title>BLOG</title>
    <style>
      body {
        text-align: center;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a href="{% url 'home' %}"><img src= "{% static 'ironmen.jpg' %}" alt='' height=50px width=70px></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:new' %}">new_post</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <div style="margin-right: 10px; text-align: right; margin-top: 15px;">
            <div href="#" tabindex="-1" aria-disabled="true">{{request.user}}님 안녕하세요!</div>
            <a href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a>
          </div>

          {% else %}

          <div style="margin-right: 10px; text-align: right; margin-top: 15px;">
            <a href="{% url 'account:login' %}" tabindex="-1" aria-disabled="true" style="margin-right: 10px;">로그인</a>
            <a href="{% url 'account:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
          </div>
          {% endif %}
          </div>
          <form class="d-flex" action="{% url 'home' %}">
            <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="query">
              <button class="btn btn-outline-success" type="submit">Search</button> 
          </form>
        </div>
      </div>
    </nav>
    <main>
      <img src= "{% static 'ironmen.jpg' %}" height="210px" width="100%">
    </main>
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>